<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent><groupId>att</groupId><artifactId>template-driven-api-testing-tool</artifactId><version>3.8.0</version><relativePath>../pom.xml</relativePath></parent>
    <artifactId>att-dist</artifactId>
    <packaging>pom</packaging>
    <name>ATT Distribution</name>
    <dependencies><dependency><groupId>att</groupId><artifactId>att-cli</artifactId><version>${project.version}</version><scope>runtime</scope></dependency></dependencies>
    <build><plugins><plugin>
        <groupId>org.apache.maven.plugins</groupId><artifactId>maven-assembly-plugin</artifactId>
        <executions>
            <execution><id>binary-release</id><phase>package</phase><goals><goal>single</goal></goals><configuration>
                <descriptors><descriptor>src/assembly/binary.xml</descriptor></descriptors><finalName>att-${project.version}</finalName><appendAssemblyId>false</appendAssemblyId><tarLongFileMode>posix</tarLongFileMode>
            </configuration></execution>
            <execution><id>source-release</id><phase>package</phase><goals><goal>single</goal></goals><configuration>
                <descriptors><descriptor>src/assembly/source.xml</descriptor></descriptors><finalName>att-${project.version}-src</finalName><appendAssemblyId>false</appendAssemblyId><tarLongFileMode>posix</tarLongFileMode>
            </configuration></execution>
        </executions>
    </plugin></plugins></build>
</project>
