<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent><groupId>att</groupId><artifactId>template-driven-api-testing-tool</artifactId><version>4.1.0</version><relativePath>../pom.xml</relativePath></parent>
    <artifactId>att-dist</artifactId>
    <packaging>pom</packaging>
    <name>ATT Distribution</name>
    <dependencies>
        <dependency><groupId>att</groupId><artifactId>att-cli</artifactId><version>${project.version}</version><scope>runtime</scope></dependency>
        <dependency><groupId>att</groupId><artifactId>att-worker</artifactId><version>${project.version}</version><scope>runtime</scope></dependency>
        <dependency><groupId>att</groupId><artifactId>att-server</artifactId><version>${project.version}</version><type>war</type><scope>runtime</scope></dependency>
    </dependencies>
    <build><plugins><plugin>
        <groupId>org.apache.maven.plugins</groupId><artifactId>maven-assembly-plugin</artifactId>
        <executions>
            <execution><id>module-jar</id><phase>prepare-package</phase><goals><goal>single</goal></goals><configuration>
                <descriptors><descriptor>src/assembly/modules.xml</descriptor></descriptors><finalName>att-${project.version}-modules</finalName><appendAssemblyId>false</appendAssemblyId><attach>false</attach>
            </configuration></execution>
            <execution><id>local-release</id><phase>package</phase><goals><goal>single</goal></goals><configuration>
                <descriptors><descriptor>src/assembly/local.xml</descriptor></descriptors><finalName>att-${project.version}-local</finalName><appendAssemblyId>false</appendAssemblyId><attach>false</attach><tarLongFileMode>posix</tarLongFileMode>
            </configuration></execution>
            <execution><id>server-release</id><phase>package</phase><goals><goal>single</goal></goals><configuration>
                <descriptors><descriptor>src/assembly/server.xml</descriptor></descriptors><finalName>att-${project.version}-server</finalName><appendAssemblyId>false</appendAssemblyId><attach>false</attach><tarLongFileMode>posix</tarLongFileMode>
            </configuration></execution>
            <execution><id>source-release</id><phase>package</phase><goals><goal>single</goal></goals><configuration>
                <descriptors><descriptor>src/assembly/source.xml</descriptor></descriptors><finalName>att-${project.version}-src</finalName><appendAssemblyId>false</appendAssemblyId><attach>false</attach><tarLongFileMode>posix</tarLongFileMode>
            </configuration></execution>
        </executions>
    </plugin></plugins></build>
</project>
