package att.server;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

/** H2-backed bounded control-plane metadata store. Evidence remains on disk under each job directory. */
final class JobStore implements AutoCloseable {
    private final String url;
    JobStore(ServerConfig config) throws Exception {
        Class.forName("org.h2.Driver");
        url="jdbc:h2:file:"+config.dataDir.resolve("db/att-server").toString().replace('\\','/')+";DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=FALSE";
        java.nio.file.Files.createDirectories(config.dataDir.resolve("db"));
        try(Connection c=connect(); Statement s=c.createStatement()) {
            s.execute("CREATE TABLE IF NOT EXISTS jobs (job_id VARCHAR(80) PRIMARY KEY, command VARCHAR(16) NOT NULL, package_id VARCHAR(64) NOT NULL, principal VARCHAR(256) NOT NULL, status VARCHAR(24) NOT NULL, created_at VARCHAR(40) NOT NULL, started_at VARCHAR(40), finished_at VARCHAR(40), worker_pid BIGINT, worker_start_time VARCHAR(40), att_version VARCHAR(32) NOT NULL, exit_code INT, result_json CLOB, diagnostic_json CLOB, performance_json CLOB, request_summary CLOB NOT NULL)");
            s.execute("ALTER TABLE jobs ADD COLUMN IF NOT EXISTS worker_start_time VARCHAR(40)");
            s.execute("ALTER TABLE jobs ADD COLUMN IF NOT EXISTS att_version VARCHAR(32) DEFAULT 'unknown' NOT NULL");
            s.execute("ALTER TABLE jobs ADD COLUMN IF NOT EXISTS performance_json CLOB");
            s.execute("CREATE TABLE IF NOT EXISTS audit (audit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, principal VARCHAR(256) NOT NULL, action VARCHAR(32) NOT NULL, job_id VARCHAR(80), package_id VARCHAR(64), created_at VARCHAR(40) NOT NULL, outcome VARCHAR(32) NOT NULL)");
        }
    }
    synchronized void insert(Job job,String summary) throws Exception {
        try(Connection c=connect(); PreparedStatement p=c.prepareStatement("INSERT INTO jobs(job_id,command,package_id,principal,status,created_at,att_version,request_summary) VALUES(?,?,?,?,?,?,?,?)")) {
            p.setString(1,job.id);p.setString(2,job.command);p.setString(3,job.packageId);p.setString(4,job.principal);p.setString(5,job.status);p.setString(6,job.createdAt.toString());p.setString(7,att.Version.PRODUCT);p.setString(8,summary);p.executeUpdate();
        }
    }
    synchronized void update(Job j) throws Exception {
        try(Connection c=connect(); PreparedStatement p=c.prepareStatement("UPDATE jobs SET status=?,started_at=?,finished_at=?,worker_pid=?,worker_start_time=?,att_version=?,exit_code=?,result_json=?,diagnostic_json=?,performance_json=? WHERE job_id=?")) {
            p.setString(1,j.status);p.setString(2,text(j.startedAt));p.setString(3,text(j.finishedAt));
            if(j.workerPid==null)p.setNull(4,java.sql.Types.BIGINT);else p.setLong(4,j.workerPid);
            p.setString(5,text(j.workerStartTime));p.setString(6,att.Version.PRODUCT);
            if(j.exitCode==null)p.setNull(7,java.sql.Types.INTEGER);else p.setInt(7,j.exitCode);
            p.setString(8,j.resultJson);p.setString(9,j.diagnosticJson);p.setString(10,ServerRuntime.JSON.writeValueAsString(j.performance()));p.setString(11,j.id);p.executeUpdate();
        }
    }
    synchronized void audit(String principal,String action,String jobId,String packageId,String outcome) throws Exception {
        try(Connection c=connect();PreparedStatement p=c.prepareStatement("INSERT INTO audit(principal,action,job_id,package_id,created_at,outcome) VALUES(?,?,?,?,?,?)")) {
            p.setString(1,bounded(principal,256));p.setString(2,action);p.setString(3,jobId);p.setString(4,packageId);p.setString(5,Instant.now().toString());p.setString(6,outcome);p.executeUpdate();
        }
        long latest=0;try(Connection c=connect();Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT MAX(audit_id) FROM audit")){if(r.next())latest=r.getLong(1);}
        if(latest>0&&latest%256==0)try(Connection c=connect();Statement s=c.createStatement()){s.execute("DELETE FROM audit WHERE audit_id NOT IN (SELECT audit_id FROM audit ORDER BY audit_id DESC LIMIT 100000)");}
    }
    synchronized List<String> staleJobIds() throws Exception {
        List<String> ids=new ArrayList<>();
        try(Connection c=connect();Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT job_id FROM jobs WHERE status IN ('QUEUED','PREPARING','RUNNING')")) { while(r.next())ids.add(r.getString(1)); }
        return ids;
    }
    synchronized List<String> expiredJobIds(Instant before) throws Exception {
        List<String> ids=new ArrayList<>();
        try(Connection c=connect();PreparedStatement p=c.prepareStatement("SELECT job_id FROM jobs WHERE status IN ('PASS','FAIL','ERROR','INVALID','CANCELLED') AND finished_at IS NOT NULL AND finished_at < ? ORDER BY finished_at LIMIT 500")) {
            p.setString(1,before.toString());try(ResultSet r=p.executeQuery()){while(r.next())ids.add(r.getString(1));}
        }
        return ids;
    }
    synchronized void deleteJob(String id) throws Exception {
        try(Connection c=connect();PreparedStatement p=c.prepareStatement("DELETE FROM jobs WHERE job_id=?")){p.setString(1,id);p.executeUpdate();}
    }
    synchronized List<java.util.Map<String,Object>> staleWorkers() throws Exception {
        List<java.util.Map<String,Object>> rows=new ArrayList<>();
        try(Connection c=connect();Statement s=c.createStatement();ResultSet r=s.executeQuery("SELECT job_id,worker_pid,worker_start_time FROM jobs WHERE status IN ('QUEUED','PREPARING','RUNNING') AND worker_pid IS NOT NULL")) {while(r.next()){var m=new java.util.LinkedHashMap<String,Object>();m.put("jobId",r.getString(1));m.put("pid",r.getLong(2));m.put("start",r.getString(3));rows.add(m);}}
        return rows;
    }
    synchronized void interruptStale(String id) throws Exception {
        try(Connection c=connect();PreparedStatement p=c.prepareStatement("UPDATE jobs SET status='ERROR',finished_at=?,diagnostic_json=? WHERE job_id=? AND status IN ('QUEUED','PREPARING','RUNNING')")) {
            p.setString(1,Instant.now().toString());p.setString(2,"{\"code\":\"ATT-SERVER-INTERRUPTED\",\"summary\":\"Job was interrupted by Server restart and was not rerun\"}");p.setString(3,id);p.executeUpdate();
        }
    }
    // Status-count polling owns its connection and result data; do not serialize it on the JobStore writer monitor.
    long count(String status) throws Exception { try(Connection c=connect();PreparedStatement p=c.prepareStatement("SELECT COUNT(*) FROM jobs WHERE status=?")){p.setString(1,status);try(ResultSet r=p.executeQuery()){r.next();return r.getLong(1);}} }
    synchronized List<java.util.Map<String,Object>> list(int limit) throws Exception {
        List<java.util.Map<String,Object>> out=new ArrayList<>();
        try(Connection c=connect();PreparedStatement p=c.prepareStatement("SELECT job_id,command,package_id,principal,status,created_at,started_at,finished_at,exit_code,result_json,diagnostic_json FROM jobs ORDER BY created_at DESC LIMIT ?")) {
            p.setInt(1,limit);try(ResultSet r=p.executeQuery()){while(r.next()){var m=new java.util.LinkedHashMap<String,Object>();m.put("jobId",r.getString(1));m.put("command",r.getString(2));m.put("packageId",r.getString(3));m.put("principal",r.getString(4));m.put("status",r.getString(5));m.put("createdAt",r.getString(6));m.put("startedAt",r.getString(7));m.put("finishedAt",r.getString(8));m.put("exitCode",r.getObject(9));out.add(m);}}
        } return out;
    }
    // Job reads own their connection and result data; allow API polling alongside writes.
    java.util.Map<String,Object> get(String id) throws Exception {
        try(Connection c=connect();PreparedStatement p=c.prepareStatement("SELECT job_id,command,package_id,principal,status,created_at,started_at,finished_at,worker_pid,exit_code,result_json,diagnostic_json,att_version,performance_json FROM jobs WHERE job_id=?")) {
            p.setString(1,id);try(ResultSet r=p.executeQuery()){if(!r.next())return null;var m=new java.util.LinkedHashMap<String,Object>();m.put("jobId",r.getString(1));m.put("command",r.getString(2));m.put("packageId",r.getString(3));m.put("principal",r.getString(4));m.put("status",r.getString(5));m.put("createdAt",r.getString(6));m.put("startedAt",r.getString(7));m.put("finishedAt",r.getString(8));m.put("workerPid",r.getObject(9));m.put("exitCode",r.getObject(10));m.put("resultJson",r.getString(11));m.put("diagnosticJson",r.getString(12));m.put("attVersion",r.getString(13));m.put("performanceJson",r.getString(14));return m;}}
    }
    private Connection connect() throws Exception{return DriverManager.getConnection(url,"sa","");}
    private static String text(Instant value){return value==null?null:value.toString();}
    private static String bounded(String s,int max){return s.length()<=max?s:s.substring(0,max);}
    @Override public void close() {}
}
